# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miabi < Formula
  desc "Command-line client for the Miabi control panel"
  homepage "https://miabi.io"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miabi-io/miabi-cli/releases/download/v0.6.0/miabi_0.6.0_darwin_amd64.tar.gz"
      sha256 "a4fb2215020dafcdddfd5a7874571091075ec573576799908f92cfe6f7dafc7d"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miabi-io/miabi-cli/releases/download/v0.6.0/miabi_0.6.0_darwin_arm64.tar.gz"
      sha256 "1c2e660a054d9a7df5bd09d2353f7e81f50ce5a2ce35c9bd2999dd2e58df9815"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/miabi-cli/releases/download/v0.6.0/miabi_0.6.0_linux_amd64.tar.gz"
      sha256 "3db342a41dff405e14af5bdff8efbd68bc8fc0ff96f2e6503bfa874bab167f06"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/miabi-cli/releases/download/v0.6.0/miabi_0.6.0_linux_arm64.tar.gz"
      sha256 "3d7889f0524a40521820f8367d310e8ac412236511e7a8bdc015389cd8272ec3"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/miabi --version")
  end
end
