# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miabi < Formula
  desc "Command-line client for the Miabi control panel"
  homepage "https://miabi.io"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miabi-io/cli/releases/download/v0.12.0/miabi_0.12.0_darwin_amd64.tar.gz"
      sha256 "de316d1e07a7943ee71aa8558d91913f2ccfe3840c3634c27588ff57f3f3f05f"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miabi-io/cli/releases/download/v0.12.0/miabi_0.12.0_darwin_arm64.tar.gz"
      sha256 "fa83e6c1312d76111d05bf229454540779ebf5afd47d468663c28a037b74df58"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/cli/releases/download/v0.12.0/miabi_0.12.0_linux_amd64.tar.gz"
      sha256 "57b18474cf6835a75295f5ec5d8665346c36983f6b113dd46d6b79c41698d6ec"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/cli/releases/download/v0.12.0/miabi_0.12.0_linux_arm64.tar.gz"
      sha256 "92b892262bcd654e1043e65d62fb60835f362e024dce616efe15d86978f55779"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/miabi --version")
  end
end
