# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miabi < Formula
  desc "Command-line client for the Miabi control panel"
  homepage "https://miabi.io"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miabi-io/cli/releases/download/v0.13.0/miabi_0.13.0_darwin_amd64.tar.gz"
      sha256 "f88b0d580047dc258d63d86cd798eb759d08c2ca755774e410eee8b05e8d6819"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miabi-io/cli/releases/download/v0.13.0/miabi_0.13.0_darwin_arm64.tar.gz"
      sha256 "b35106b511f5965e419cb1d85957b9b8107a20c6face95e51d0d36ed282f42bd"

      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/cli/releases/download/v0.13.0/miabi_0.13.0_linux_amd64.tar.gz"
      sha256 "368ce9bd62ea99ac38d371136052ea16c18317d0d8c1c54c818b8c3fd00cce2e"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/miabi-io/cli/releases/download/v0.13.0/miabi_0.13.0_linux_arm64.tar.gz"
      sha256 "6e87b5b8200dfd5b53eed305ab46af689206f0ffa0a115e700667e2f9042c0e0"
      define_method(:install) do
        bin.install "miabi"
        generate_completions_from_executable(bin/"miabi", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/miabi --version")
  end
end
